# Project metadata
project_name: aleutian-trace
env:
  - CGO_ENABLED=0

# execute before the build
before:
  hooks:
    - go mod tidy

builds:
  - id: trace
    main: ./cmd/trace
    binary: trace
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: trace-mcp
    main: ./cmd/trace-mcp
    binary: trace-mcp
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: trace-proxy
    main: ./cmd/trace-proxy
    binary: trace-proxy
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

# Create the tar.gz archives
archives:
  - format: tar.gz
    files:
      - LICENSE.txt
      - README.md
      - NOTICE.txt
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - trace
      - trace-mcp
      - trace-proxy

# Generate a checksum file
checksum:
  name_template: 'checksums.txt'

# Create Git tag and Github release
release:
  changelog:
    sort: asc
    filters:
      exclude:
        - '^docs:'
        - '^test:'
        - 'merge conflict'
        - 'Merge pull request'
        - 'Merge branch'
